COMPILER=g++
PATH_TO_PROGRESSLIB=../..
ConsoleProgressBar: ConsoleProgressBar.cpp $(PATH_TO_PROGRESSLIB)/Progress.cpp $(PATH_TO_PROGRESSLIB)/Progress.h
	$(COMPILER) -o ConsoleProgressBar ConsoleProgressBar.cpp $(PATH_TO_PROGRESSLIB)/Progress.cpp $(PATH_TO_PROGRESSLIB)/Progress.h